#  ______              _        ____                      _               _
# |___  /   /\        | |      |  _ \                    | |             | |
#    / /   /  \  _   _| |_ ___ | |_) |_ __ ___   __ _  __| | ___ __ _ ___| |_
#   / /   / /\ \| | | | __/ _ \|  _ <| '__/ _ \ / _` |/ _` |/ __/ _` / __| __|
#  / /__ / ____ \ |_| | || (_) | |_) | | | (_) | (_| | (_| | (_| (_| \__ \ |_
# /_____/_/    \_\__,_|\__\___/|____/|_|  \___/ \__,_|\__,_|\___\__,_|___/\__|
#
# Configuration file for the application.

# Time in seconds between each broadcast.
interval: 300